# Generated by Django 4.2.19 on 2025-04-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
